services:
  order-postgres:
    ports:
      - "${ORDER_DB_PORT:-54329}:5432"

  storage-postgres:
    ports:
      - "${STORAGE_DB_PORT:-54330}:5432"

  cart-postgres:
    ports:
      - "${CART_DB_PORT:-54331}:5432"

  payment-postgres:
    ports:
      - "${PAYMENT_DB_PORT:-54332}:5432"

  notification-postgres:
    ports:
      - "${NOTIFICATION_DB_PORT:-54333}:5432"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"

  minio:
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"

  kafka:
    ports:
      - "${KAFKA_HOST_PORT:-9092}:9092"

  order-service:
    ports:
      - "${ORDER_SERVICE_PORT:-8080}:8080"
      - "${ORDER_GRPC_PORT:-9094}:9094"

  storage-service:
    ports:
      - "${STORAGE_SERVICE_PORT:-8081}:8081"
      - "${STORAGE_GRPC_PORT:-9090}:9090"

  cart-service:
    ports:
      - "${CART_SERVICE_PORT:-8083}:8083"
      - "${CART_GRPC_HOST_PORT:-9093}:9091"

  payment-service:
    ports:
      - "${PAYMENT_SERVICE_PORT:-8084}:8084"

  notification-service:
    ports:
      - "${NOTIFICATION_SERVICE_PORT:-8085}:8085"

  api-gateway:
    ports:
      - "${API_GATEWAY_PORT:-8082}:8082"
